name: Build firmware

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04  # Sử dụng môi trường sạch của Ubuntu thay vì container cũ
    defaults: { run: { shell: bash } }
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Ubuntu Environment
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
          cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
          pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget

    - name: Get variables
      run: |
        sed -i 's|\r$||g' variables build.config
        . <(cat variables build.config)
        PADAVAN_THEMES="${PADAVAN_THEMES[*]}"
        for v in "${!PADAVAN_@}" "${!CONFIG_@}"; do
          echo "$v=${!v}" >> $GITHUB_ENV
        done

    - name: Download sources and toolchain
      run: |
        git config --global --add safe.directory '*'
        # Clone mã nguồn của keke1023 về thư mục tên là 'padavan'
        git clone --depth 1 https://github.com/keke1023/Padavan.git padavan
        
        # Di chuyển vào thư mục toolchain mới và chạy script để tải nhanh toolchain về
        cd padavan/toolchain-mipsel
        sh dl_toolchain.sh

    - name: Install themes
      run: |
        if [[ -n $PADAVAN_THEMES ]]; then
          git clone --depth 1 -b "$PADAVAN_THEMES_BRANCH" "$PADAVAN_THEMES_REPO" themes
          cp -r themes/common-theme themes/jquery.js padavan/trunk/user/www/n56u_ribbon_fixed

          for theme in $PADAVAN_THEMES; do
            echo "Installing $theme theme"
            cp -r "themes/$theme-theme" padavan/trunk/user/www/n56u_ribbon_fixed
          done
        fi

    - name: Run custom pre-build script
      run: '[[ -f pre-build.sh ]] && . pre-build.sh || :'

    - name: Build firmware
      run: |
        # Đưa file cấu hình vào thư mục trunk của mã nguồn keke1023
        cp build.config padavan/trunk/.config
        cd padavan/trunk
        
        # Chạy lệnh xóa rác và tiến hành build firmware
        ./clear_tree
        ./build_firmware
        
        FW_FILE_NAME="$(find images -type f -regextype posix-extended -iregex ".*\.(trx|bin)$" \
                        -printf "%T@\t%f\n" | sort -V | tail -1 | cut -f2)"
        [[ -n $FW_FILE_NAME ]] || { echo "Firmware file not found"; exit 1; }
        echo "FW_FILE_NAME=$FW_FILE_NAME" >> $GITHUB_ENV

    - name: Run custom post-build script
      run: '[[ -f post-build.sh ]] && . post-build.sh || :'

    - name: Prepare artifacts
      run: |
        cp "padavan/trunk/images/$FW_FILE_NAME" .
        echo "BUILD_TIMESTAMP=$(date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: padavan_${{ env.CONFIG_VENDOR }}_${{ env.CONFIG_FIRMWARE_PRODUCT_ID }}_${{ env.BUILD_TIMESTAMP }}
        retention-days: 7
        path: |
          ${{ env.FW_FILE_NAME }}
          build.config
